@KK.Agent.WebAPI_HostAddress = http://localhost:7084

###
POST {{KK.Agent.WebAPI_HostAddress}}/chat/stream
Accept: application/json
Content-Type: application/json

{
    "sessionId": "",
    "message": "Where does Luke Skywalker come from? Tell me about his home planet"
}

###
POST {{KK.Agent.WebAPI_HostAddress}}/chat
Accept: application/json
Content-Type: application/json

{
    "sessionId": "",
    "message": "Hello World!"
}