@KK.Agent.WebAPI_HostAddress = http://localhost:5041

###
POST {{KK.Agent.WebAPI_HostAddress}}/chat/stream
Accept: application/json
Content-Type: application/json

{
    "sessionId": "",
    "message": "Hello World!"
}

###
POST {{KK.Agent.WebAPI_HostAddress}}/chat
Accept: application/json
Content-Type: application/json

{
    "sessionId": "",
    "message": "Hello World!"
}